### ISSUE TITLE
Incompatibility with latest (515) DM compiler

### ISSUE THREAD

**Issue by NK1605** [SPLURT-Station/S.P.L.U.R.T-Station-13#1102]
## Reproduction:

Downloading the master branch of the code (updated 3 days ago as of writing this)
running byond updated to [515.1633]

upon running build.bat, the following log appears (.txt file)

however, when building using 514.1589, no errors/warnings appear, and the dmb is built correctly
[log.txt](https://github.com/SPLURT-Station/S.P.L.U.R.T-Station-13/files/14517838/log.txt)

**Comment by liz-lavenza** [comment]
Does this still happen?

**Comment by NK1605** [comment]
just compiled it on compiler  515.1639, it built with no errors, and other than some unknowns on the config files for cryo, it had no runtimes
