### ISSUE TITLE
[BOUNTY] Misc Edward Bounties (Minesweeper, Hypnovisors, Modular Computer Dating App)

### ISSUE THREAD

**Issue by Grant4455** [SPLURT-Station/S.P.L.U.R.T-Station-13#19]
$5 - Port minesweeper to the new codebase. I love tetris, but I want to be able to sweep mines AND play Tetris. I'd up this to a $15 bounty if it came attached with a tablet version of the program similar to the Donksoft Arcade.
$10 - Port the hypno-visors from skyrat. Simple as, really.
$40 - Tablet/Laptop/Modular computer programme dating/hookup app. Bonus if it has an open chatroom option

All payments completed on PR, even if not merged, provided the code works. Payment via paypal.

**Comment by SandPoot** [comment]
Minesweeper was removed for reportedly being bad for the entire server, recently wasn't working well and... [info here](https://github.com/Citadel-Station-13/Citadel-Station-13/pull/15232)

**Comment by StrangeWeirdKitten** [comment]
I plan on porting the hypnovisors as conjunction with other stuff found in #24

**Comment by Grant4455** [comment]
I'm sorry for my delay in getting back to you SWK, if you'd like to get in contact with me on the discord (Edward on the staff team), I can get the bounty paid up.
