### ISSUE TITLE
[BOUNTY] $5 Add cuddling as an ERP verb

### ISSUE THREAD

**Issue by toastywaffelz** [SPLURT-Station/S.P.L.U.R.T-Station-13#266]
## Contact:
Slugcat#1724  (Felix Caito)

## About the Bounty
Make it so you can verbspam cuddling people. I promise this is a feature we want.
Suggestions for cuddling messages:
X nuzzles Y fondly.
X cuddles Y.
X caresses Y in a soft embrace.

I'm sure there's other cute cuddle messages you can come up with, be creative!

Reward: $5 
PayPal only

Deadline: April 30th

**Comment by radar651** [comment]
Someone using the bounty system? And being reasonable about it? yeah okay, I will look it into myself.
