### ISSUE TITLE
Synthetic Anthromorph Character Appearence unable to select Tails, snouts, and tauric bodies.

### ISSUE THREAD

**Issue by Redrover1760** [SPLURT-Station/S.P.L.U.R.T-Station-13#289]
## Round ID:
[878](https://scrubby.melonmesa.com/round/878)

## Testmerges:
https://github.com/SPLURT-Station/S.P.L.U.R.T-Station-13/pull/286

## Reproduction:
Synthetic Anthromorphs are incapable of selecting tails, snouts, and tauric bodies. Go onto the server, select Synthetic Anthromorph as your species, attempt to modify tail, snout, and tauric body. Instead of showing options, all it shows is "none".

I was able to modify these before, but now I cannot. You can get around it by switching to an anthromorph, selecting what you want, and then switching back and then back or simply already having these features.

**Comment by Commondragon** [comment]
If you select "show mistmatched markings" they show up.  It's been like this for a bit.

**Comment by Redrover1760** [comment]
Ah.

That works.
