### ISSUE TITLE
Dullahans are broken.

### ISSUE THREAD

**Issue by Gamer-Johnson** [SPLURT-Station/S.P.L.U.R.T-Station-13#292]
## Round ID:
[914](https://scrubby.melonmesa.com/round/914)

## Testmerges:
#286 

## Reproduction:
Dullahan head mechanics don't work correctly. Vision works more or less as it should although you do have to toggle back and forth once to get the camera to track your head instead of your body, but hearing and speech are broken. The head does hear speech correctly, but the body hears sound effects and speech comes from the body as well. Easily reproducable by making a dullahan character, leaving your head on the floor, and talking/making sound effects at different distances from your head.

**Comment by Yatiyaya** [comment]
This is due to the halloween races being defunct. I'm going to slowly fix them over time, so. Here's hoping.
