### ISSUE TITLE
[BOUNTY] 20$ Port a skyrat character accessory/addon

### ISSUE THREAD

**Issue by Aphast** [SPLURT-Station/S.P.L.U.R.T-Station-13#351]
## Contact:
Aphast#7266 on discord

## About the Bounty
So fer 20 bucks ill pay for someone to port an old donor thing of mine, a sylveon neck and head bow from SR, unsure if it will require a shitton of work or not but presumably they can both be added to the decorative wings slot, the exact code for them is [here ](https://github.com/Skyrat-SS13/Skyrat-tg/blob/9c738967a13ecefb226bc0b244c5a0b5d8c2a834/modular_skyrat/modules/customization/modules/mob/dead/new_player/sprite_accessories/neck_accessory.dm) with sprites being [here](https://github.com/Skyrat-SS13/Skyrat-tg/blob/9c738967a13ecefb226bc0b244c5a0b5d8c2a834/modular_skyrat/master_files/icons/mob/sprite_accessory/neck_accessory.dmi) ayo bt-dubbs dont make it a donor item only as that wasnt my intention with it in SR in the first place, theoretically it could also be used in a wing-slot as a new type instead of being an accessory, paypal aswell and deadline is i dont give a shid, amount paid might very depending on speed but not below 20

**Comment by BongaTheProto** [comment]
Why on the decorative wings slot tho? it could pretty well be just a neck accessory

**Comment by Aphast** [comment]
im frankly unsure we have a neck and head accessory slot
