### ISSUE TITLE
[BOUNTY - COMPLETE!] $100 Chastity system--to include cages, belts, chemicals, and possibly other factors

### ISSUE THREAD

**Issue by Cleric2145** [SPLURT-Station/S.P.L.U.R.T-Station-13#383]
## Contact:
Cleric#2145

## About the Bounty
Available for partial completion, preferably 'External' items first. Porting of Skyrat assets and code is recommended.
Price negotiable contingent on speed and unexpected complexity.

### Necessary resources: 
- Code 
- Sprites
- Sex Mechanics Integration
- Flavor text
- UI Elements preferred
- Possibly Chem recipes

### Premise:

- Two types of chastity, External and Internal. Available in Kinkmate machines, some only after hacking.
- ($40) External include devices; chastity cages, chastity belts. Physically prevent touching of the sexual organ, prevent penises from becoming erect (?) and both provide flavor text on a regular basis regarding their discomfort or embarrassing nature. Potentially an easy implementation by forcing genitals to 'Never Visible' and locking chastity clothing in place. When aroused or sexually interacted with, flavor text becomes more explicit and frequent before fading over time with arousal. Comes with keys, goes in underwear slot? Would be preferable to fit below underwear and 'replace' genital appearance while worn, and ideally prevent players from using "Always Visible" to bypass. 
- ($60) Internal includes chemicals or hypno (This may be more work than expected, depending on timeframe and amount of required work, could be spread into a second bounty in favor of finishing External Chastity first.) These allow touching of the organs, but changes how the genitals can produce arousal or appear aroused. Provides flavor text about being unable to orgasm and remaining frustrated. Ideally can designate certain methods of orgasm. For instance, one chemical prevents penis orgasm, another prevents nipple, etc.

### Proposed External Items ($40):

- Chastity Cage: Standard Cages, prevents use/stimulation of penis. Ideally polychromic, otherwise pink, purple, black. Can be removed with key or with wirecutters (possible feature.)
- Metal Cage: Metal cage, different sprite, small chance of flavor text about "Player jingles slightly as they move." Chance rises with move speed? Requires welding tool to remove w/o key (possible feature.)
- E-Stim Cage (Hacked Kinkmate): (May be more effort, willing to discuss) Plastic Cage, requires wirecutters w/o key(poss.) Links to signaler frequency. Possibly can be switched between stimulation and shock. Shock reduces arousal (except for masochists), causes shaking and gasp/whimper/etc. with painful flavor text. Stimulation increases arousal with blush/moan/etc. Possibility of dedicated remote item (like mind collar) that would provide UI with all the above options and strength of effect. (High power shock could essentially work like shock collar, low is purely anti-arousal. High power stim is like two high power large vibrators, low is like one egg on low.)
- Chastity Belt: Requires welder to remove w/o key(?) and can individually toggle block for vagina, penis, testicles, or anus prior to attachment. Blocked genitals will also lock in place other equipment (buttplugs, vibrators, etc.). Portal panties optimistically could be locked in place as well?

### Proposed Internal Items ($60):

- [UI] Genital Arousal Permission (GAP) Menu: General UI window to choose hypno settings for each genital (Similar layout to the visibility selection menu) Could also be integrated to existing hypno devices. 
> Hyper-Sensitive - Genital multiplies arousal gains by 3x (Makes you cum quickly from that genital)
> Full-orgasm - Genital behaves normally
> Disappointing Orgasm - Genital produces 0.75x arousal, orgasm has embarrassing flavor text and produces 0.5x fluid.
> Edge Only - Genital produces 0.5x arousal, cannot raise above 80% of orgasm arousal. (Negotiable if coding is troublesome.)
> Unarousable - Genital produces no arousal, no sensation, cannot display aroused state, when exposed will produce embarrassing flavor text when trying to stimulate, and when orgasm occurs (for penis and vagina primarily.)

- [Hypno] Hypnotic Chastity Magazine (Hacked Kinkmate): Can simply use existing sprites colored pink for simplicity. First use opens the GAP menu. Once choices locked in, magazine turns into a renamable lewd adult magazine for trickery purposes (still asks for hypno consent. Without hypno perms or with declined hypno offer, just provides flavor text similar to "You skim the magazine, but the images seem oddly covered by twisting spirals that cover the 'most interesting' bits. You were only reading it for the articles anyways...")
- [Hypno] Hypnotic Chastity Watch: Same as standard Mesmatron (or perhaps just an additional option on the normal watch), possibly reskinned to be silver? Instead of free-text prompt during hypnotism, will open the GAP menu for the hypnotised party.

- [Chem] Penis Purity (Chastity Draft+Camphor): Disables arousal/orgasm from penis/testicle use, slow decay in body. Comes in 30u bottle, purple fluid.
- [Chem] Virtuous Vagina (Modesty Milk+Camphor): Disables arousal/orgasm from penis/testicle use, slow decay in body. Comes in 30u bottle, pink fluid.
- [Chem] Anal Allure (Hacked KinkMate or Hexacrocin+Chastity Draft): Significantly increases arousal gain from anus. Possibly decreases gain from vagina/penis/testicles? Dark Red Fluid 30u
- [Chem] Breast Buzzer (Hacked or Hexacrocin+Succ Milk): Significantly increases arousal gain from nipples/breast. Possibly decreases gain from vagina/penis/testicles? Light Pink Fluid 30u
- [Chem] Hexacamphor (Existing chem, modified/made available.): Simply make Hexacamphor available in Kinkmates. In contrast to Hexacrocin, will potently reduce/prevent arousal gain and orgasm. If 30u or greater is in a mob's system, they become equivalently 'addicted' and receive reduced arousal from all sources to scale with overdose, craves more in order to continue being a good boy/girl/slave. Perhaps reversible (and reverses) with hexacrocin, i.e. cancel out each other? If you've taken 60u of Hexacro, all effects (except brain damage) can be cancelled out by 60u of Hexacam with no effects of the Hexacam overdose (since they effectively neutralize each other like acids/bases.)
- [Chem] Chastity Draft/Modesty Milk (Hacked Vendor) - Growth serums already present. Why not add dinky shrinkies and titty tamers?

**Comment by Cleric2145** [comment]
I stupidly hit ctrl+enter somehow. I'm still working on the post until I comment otherwise.

**Comment by Cleric2145** [comment]
Go for it! I want this to be satisfying for everybody.

**Comment by Gamer-Johnson** [comment]
Alright, my idea is basically for the belts to be modular. Like you said, you should be able to toggle what parts get blocked by the belt before you put it on. I think it would be best if the core item of the belt couldn't block anything by itself, but it comes in a box with shields for every part (anus, vagina, penis, testicles, etc.) that you can attach to the belt before putting it on. The shields themselves would have attachment points for other items, like portals and dildos. Hacking the vendor would reveal a new box of extra parts for the belt that do different things on top of the normal functionality like stimulate or shock the wearer. These could be set to go off randomly or at regular intervals, or be set up with a signaler, and the vibrator or whatever it ends up being could also be set to run constantly like the vibrators on skyrat but with different settings. The standard high, medium, and low would be great but I think it would be cool if there were a setting that tries to edge you indefinitely. The edging setting could probably even recycle some code from the hypno chastity stuff too depending on how it gets done.

**Comment by Cleric2145** [comment]
I like the idea, I just feel like it'd be a massive increase to the amount of work for the whole system. I think after we get _some_ kind of chastity system in place, we could bounty/request that sort of thing. Maybe when somebody takes on the bounty, we could discuss exactly how difficult that'd be, but I feel like that might be a big ask. I **do** like it, though!

**Comment by JerryWester** [comment]
~~Dammit, stop giving me more kinks to be interested in, I have too many as it is~~

I'm personally not a huge fan of chastity cages/belts, but the idea of the e-stim cage and GAP has me interested... Almost concerningly so. I may take a look into this for my own enjoyment. Though, I know nothing about how the HTML UI stuff functions so no promises about things looking pretty or being entirely functional.

**Comment by Cleric2145** [comment]
Bounty upped to $100USD ($40/$60)

**Comment by Zirok-BYOND** [comment]
Apparently being worked on by @WoolyAypa

**Comment by Cleric2145** [comment]
PR submitted! Thank you!
https://github.com/SPLURT-Station/S.P.L.U.R.T-Station-13/pull/633
