### ISSUE TITLE
Discord link is broken.

### ISSUE THREAD

**Issue by Maxwellneo** [SPLURT-Station/S.P.L.U.R.T-Station-13#384]

**Comment by Maxwellneo** [comment]
I guess GitHub is the only way to communicate with you.

**Comment by BongaTheProto** [comment]
Both the link in the hub in the one in the github readme are still functional

**Comment by Maxwellneo** [comment]
Strange. When I press "accept" there's nothing happens.
![IMG_20220621_180420](https://user-images.githubusercontent.com/75709578/174955503-85221402-f871-4581-87a0-97b562b25de6.jpg)
Yeah, I'm Russian. Anyway, I have no idea why I can't join.
As I said earlier the discord support said that links are broken... Maybe I should try to join with VPN?

**Comment by Maxwellneo** [comment]
I tried to use VPN. Nothing changes.

**Comment by BongaTheProto** [comment]
> I tried to use VPN. Nothing changes.

what is your discord account?

**Comment by Maxwellneo** [comment]
@Neon_Maxwell

ср, 22 июн. 2022 г., 11:21 BongaTheProto ***@***.***>:

**Comment by Maxwellneo** [comment]
@Neon_Maxwell#0195

ср, 22 июн. 2022 г., 11:28 MotoBUG ***@***.***>:

**Comment by Maxwellneo** [comment]
So... What's your account?

**Comment by Maxwellneo** [comment]
So, how is it? Is there other ways to join the discord server?

**Comment by Maxwellneo** [comment]
And sorry if I am annoying.

**Comment by Maxwellneo** [comment]
THANKS FOR HELP!
