### ISSUE TITLE
[BOUNTY] DULLAHAN SPECIES IMPROVEMENTS 75 usd (negotiable)

### ISSUE THREAD

**Issue by ImmovableSaint** [SPLURT-Station/S.P.L.U.R.T-Station-13#406]
## Contact: DULLAHAN IMPROVEMENTS BOUNTY 75 USD 

Hit me up, at The Immovable Saint#0001 my discord. My Ckey is MagpieMayhem

## About the Bounty
Dullahan race is cool and good but they're severely hindered for a lot of things, making work with them very hard. They can't wear anything on their head, hats, welding helmets (They do get blinded by the spark), HUDs, not even headsets. Could this be fixed maybe? Allow the Dullahans to wear these things? Maybe letting them equip headgear for their mechanical purposes but making them invisible so it doesn't look like the equipment is floating in the air? Or maybe just allow heads to equip stuff.
Also, they speak from their body, that should be changed so they speak from their head instead, would be funny to see a head on the floor like, "Hey, have you seen my body?" and it would make more sense than a headless body talking.

- Modular head
Able to have 'slots' to put things onto their head sprite, goggles hats ect

-Speaks from the head 
can hear me and subtle/ghost subtle from head, talks from the head, hears/sees from the head. Make it harder to see when head is in a bag of holding, but add a harness option maybe to make holding onto the head easier

-feels from the body 
When in body cam can see /me and /subtle but is unable to hear "so and so is talking but you cant hear it" more inducive for rp if the head gets seperated from the body.

- positive points in traits for being a dullahan. Because holding the head is a handicap. make sight worse in a bag, should get some points to balence it out like +2 or 3

-Usable head
for erp purpouses one should be able to use the head 'item' like a fleshlight if lewd verbs are allowed if targeting groin, should also be able to 'kiss' them if targeting face

I'm open to Ideas on how to impliment things and I'm great at communication, you just need to messege me on discord.
I'm willing to up the bounty reward if the work exceeds that of 75 usd's worth. 
Anything with this that needs sprited I can sprite (ex the harness)

EDIT:  May need to add new ways to revive from death, not having a brain means one can't be Defibbed or SR-ed

**Comment by Gamer-Johnson** [comment]
I've been waiting for this for so long. The one thing that I'd like to see outside of what's in the bounty is a non-undead dullahan race, like a portal/bluespace variant that is just an ordinary human whose head is just detached via portals or bluespace bullshittery.

**Comment by ImmovableSaint** [comment]
This could probably be done seperately, like a fleshlight portal type toy thing after once i've worked all the funny kinks out of the race.

**Comment by ImmovableSaint** [comment]
Thats totally fair, if i get someone interested in the bounty I might consider adding the eating thing, but I personally like not having to breath, i feel like it would have to be some weird mechanic with spacesuits that I don't wanna bother with to be honest. Because I like being able to go on Lavaland and into space as an engineer. Though I probably won't make the head wearable, i just feel like it doesnt fit the idea of a dullahan too well. like yea I've seen it in media and art but im going for purest "headless horsemen" Type. I think it makes the species more intrigueing vs, hey lol look a party trick i can do, *pops head off* lmao.

**Comment by Gamer-Johnson** [comment]
What I'm talking about is a second, separate non-undead dullahan race, so there'd be the undead one we already have and a new one that needs to eat and breathe. As far as I can tell, it's actually mostly just a copypaste job so I *might* be able to do it myself once this bounty is claimed unless it gets done along with the bounty.

**Comment by Gamer-Johnson** [comment]
I was already planning on giving the living variant a different name. If it's as easy as I think it is, I probably will go ahead and make living and undead anthromorph dullahan variants as well. Of course that would leave us with 4 different dullahan races, but hey more variety is generally a good thing.

**Comment by Zirok-BYOND** [comment]
First line has no contact information

**Comment by ImmovableSaint** [comment]
Fixed

**Comment by ImmovableSaint** [comment]
To be honest @Gamer-Johnson Too many Dullhan subspecies might cause issues, but its really up to mosley what gets added to the game.
