### ISSUE TITLE
[BOUNTY] $20 Porting Cortical Borers (negotiable)

### ISSUE THREAD

**Issue by CinKro** [SPLURT-Station/S.P.L.U.R.T-Station-13#409]
## Contact:  
CinKro#1001

## About the Bounty
Porting the Cortical Borers from 2017 tg station, the wiki entry for them is still up and I think it would be a great antag to have access to for RP and ERP purposes. Would basically be the version of Cortical Borers before TG removed them in 2017 with the addition of hexacrocin and crocin injection as well as reproduction no longer leaving vomit on the ground. Payment is negotiable if it ends up taking longer than expected.

**Comment by CinKro** [comment]
I have just learned that skyrat also apparently has cortical borers, porting it from there would also suffice.

**Comment by catrock31** [comment]
https://ss13.moe/wiki/index.php/Borer

**Comment by Turtle567** [comment]
I'll take a look at the TG code but I doubt Borers are still kicking around in there. Do you know if Skyrat currently has Borers enabled?

**Comment by Turtle567** [comment]
Gave it a try but came up short, all the Cortical Border code can be found here:
https://github.com/tgstation/tgstation/pull/21118/files
It's outdated though and probably needs some major changes, good luck to whoever takes the bounty.
