### ISSUE TITLE
[BOUNTY] $30 Create a Rapid Tile Layer

### ISSUE THREAD

**Issue by Looking4bros** [SPLURT-Station/S.P.L.U.R.T-Station-13#424]
## Contact:  

Looking4bros#4511 I am also Craig Smith in game and as my discord server nickname.

## About the Bounty

The idea is to duplicate the Quality of Life improvement the Rapid Cable Layer brought to wiring solars, to tiling maint, and other new construction places. Requirements of the tool consist of, being able to dispense more tiles than a single stack, accepting Metal as a source of fuel/ammo, and for it to lay tile as you walk, without having to click on each section of plating, as the Rapid Cable Layer does. The Rapid Cable layer only lays cable automatically when wielded, that kind of distinction would be preferred, but a activate in hand on/off would be acceptable.

- Dispense/hold more than 60 tiles (240 would be fantastic, as that is the same ratio that the Rapid Cable layer has with it's capacity)
- Accept metal sheets as a means to refill the tool
- Automatically lay tiles as you walk, toggled either by wielding it, or activating it in hand.

I am willing and able to pay 30 United States Dollars, via Paypal. or... some other convenient way of getting money to you. *shrugs*

**Comment by Zirok-BYOND** [comment]
This needs to be closed as it#s been taken already.
