### ISSUE TITLE
(BOUNTY) The addition of a new role! "Stowaway" (35$ USD)

### ISSUE THREAD

**Issue by Solaire-dahsun** [SPLURT-Station/S.P.L.U.R.T-Station-13#453]
## Contact: 
Discord Solaire#1337 
And CKEY Sammy nekos

## About the Bounty
This NEW role would be a fun and hopefully engaging way for  players to add more to roleplay in a non destructive means but at the same time being able to have more interesting interactions with security. 
This new role consists of being a as the title would suggest a Stowaway on the station that is there illegally. HOWEVER this is a NON antag role that allows them to get captured or run from security giving the willing officers something to do aswell as a fluid and easy transition to the entire AP punishment system we have implemented 

Effectively it would be a round start only job that admins could add more slots to much akin to perma inmates with far more intractability as they would receive no ID or radio and be stuck in maintance only with some basic tools to hack doors and move about. Relying on the kindness of other maintance dwellers or running from the watch full security members.  When the round spawns they get the same form of perma inmate text making it VERY clear that they are not a Antag and to NOT break server rules.
And per request I am adding a small addendum and context. When joining as a perma inmate currently you get big BOLD red text telling you the player not to break the server rules and not attempt break outs. For this role we simalarly could use the same system to CLEARLY state "You are a stowaway. You should NOT be starting fights or attempting to fight security for any reason. At best you should be actively on the run from them as you are on the station illegally

**Comment by Zirok-BYOND** [comment]
What exactly would prevent them from taking the ID of a 20m SSD crewmember? Maintenance access would be highly desirable for them so I'd expect them to do this.

**Comment by Solaire-dahsun** [comment]
> What exactly would prevent them from taking the ID of a 20m SSD crewmember? Maintenance access would be highly desirable for them so I'd expect them to do this.

The basic rules of the server... Admins get logs when people take shit off a person thats SSD. Same goes for ANYONE stealing shit from a SSD person. Since I know some security members will steal money from SSD people to buy weapons from cargo.
