### ISSUE TITLE
[BOUNTY] $75 Bimbofication Rework (Amount Negotiable)

### ISSUE THREAD

**Issue by Drayco84** [SPLURT-Station/S.P.L.U.R.T-Station-13#567]
## About the Bounty

Requesting a rework of the Bimbofication mechanics. According to Word of Mosley, all it currently does is cause brain damage. For obvious reasons, this is incredibly boring and not fun. So, I'm proposing for removal of the brain damage and for Bimbofication to apply following changes, preferably over the course of some time to ensure that the transformation is spaced out and not instant. (This is also to ensure that the player isn't overwhelmed by these changes all at once.) Probably SHOULD have some kind of surgery available to revert Bimbofication effects for the sake of RP purposes, but as a reminder this is a pref that has to be enabled because it's not allowed by default.

**Phase 1: Warning. Character is starting to turn Bimbo and should get that fixed if it's undesired.**
-Character becomes permanently aroused and gets notices that stack with crocin or hexacrocin in their system notifying them that they need or are craving sex. (Maybe some custom arousal text like how nipples are hard and/or the vagina looks swollen with need
-Applies "Dumb for Cum", "Extra-Productive Genitals", "In-Heat", and "Nymphomanic" trait effects that stack with the original traits. (Might use the original text for the traits on round start, or a notice that said trait is getting stronger if the player already has said trait.)

**Phase 2: Slipping. Character is sliding towards their new Bimbo personality and lifestyle.**
-Causes breast and butt expansion to a certain minimum. (Probably +1 to maybe +3 breast sizes and +1 or +2 ass size. Growth limit prefs are being added via a previous bounty that's in development.)
-Halve Lust Tolerance (So if it was set at 200 it's now 100, and if it was set at 75 it's now 37.5.) and double Sexual Potency. (10 becomes 20, 25 becomes 50) Yes, these go past the values you can actually set in Character Appearance.
-Positive moodlet if the character has cum inside them.

**Phase 3: Full Bimbo!**
-Change chat color to bright pink. This is accompanied by randomly giggling and adding "Like" to dialog, similar to how zombies randomly add "Brains...". (Would prefer to change language to something like Valley Girl or Bimbospeak, dunno how difficult it would be to implement.)
-Character takes notice of any exposed male members in their vision via text notification, and other nearby players (Speaking range.) are also alerted of the bimbo's attention.
-Massive smattering of new moodlets...
_Negative:_
The character doesn't have cum in ANY of their genitals. (Aside from cum in their own balls, if they have them.)
Character isn't wearing a sexy outfit or their any of their genitals aren't exposed. (This might be optional depending on difficulty to implement and maintain unless a class or tag can be assigned to outfits like "Sexy".)
_Positive:_
Character gets a stacking bonus for cum in -each- hole/orifice/genital with an additional bonus if all of them are filled. (Except a penis, dunno how to toggle a pref for this one...)
Character has lipstick ("My lips are ready for sucking, tee-hee!") and/or nail polish ("My nails are so pretty!") applied.
Mood bonus for each genital that's on display, with an additional bonus if they all are. (Exceptions for "Always Hidden" genitals for those "sometimes" herms or femboys.)

Override moods, giving a penalty if there's not been any cum recently stuffed into a hole and if the tits, ass, and cock/vagina aren't exposed. Conversely, get a stacking mood boost if all genitals (Tits, ass, vagina, and cock.) are exposed with a bonus moodlet if everything is on display. Also get mood boosts if vagina, ass, and belly are filled with cum with an additional bonus moodlet if all three are filled.

**Comment by GigaDrayco** [comment]
Okay, due to some issues with my old email address, I will be using this account for communication instead. Your best bet to contact me is still through Drayco#0739 @ discord. Just send a PM, please.

**Comment by GigaDrayco** [comment]
I'm requesting that this bounty be closed as I'm no longer interested in seeing this happen. As I also no longer have access to the old email and github account, I can't do this myself.
So, any admins able to help me out on this?

**Comment by Drayco84** [comment]
Hey, I'm able to get into my original email account again! Time to close this and wrap up the loose end.
