### ISSUE TITLE
[BOUNTY] $20 (Per Shape Set) Size F to O Sprites for Quad and Sextuple Breast Shapes

### ISSUE THREAD

**Issue by GigaDrayco** [SPLURT-Station/S.P.L.U.R.T-Station-13#622]
## Contact:
Drayco#0739

## About the Bounty
I want sprites for the Quad and Sextuple breast shapes so they stop completely disappearing when they hit F cup size and beyond. I'm aware that this is a terrible rate per sprite ($2 each.) but it's kinda financially stretching things for me as they are and this has been bothering me since I joined the server over a year ago.
Amount will be paid when usable in-game and most likely via paypal, but other options are open. If this feels too scammy, the amount can be pre-paid to Mosley who can hold onto the funds until the sprites are implemented into the game and the bounty can be claimed.
If there's any questions, please PM me on Discord at Drayco#0739.

**Comment by FelixBardner** [comment]
I may be new to adding stuff to byond, but this doesn't seem like a bad place to start. I'm on it. I'll let you know how it goes.

**Comment by GigaDrayco** [comment]
Crap, I completely forgot. Uhm, if you're still interested please reach out to me on Discord if you haven't already.

**Comment by GigaDrayco** [comment]
Oh, so THAT'S what that button does!

**Comment by GigaDrayco** [comment]
Fulfilled by WoolyAypa. Thanks a ton, man.
