### ISSUE TITLE
i beg of you can we fix crew monitors

### ISSUE THREAD

**Issue by zeroisthebiggay** [SPLURT-Station/S.P.L.U.R.T-Station-13#726]
## Round ID:

doesn't matter

## Testmerges:

doesn't matter

## Reproduction:

open a crew monitor
watch as every single person `(almost the entire round)` with a custom title manifests near the top of the crew monitor with big bolded orange text as the game doesn't recognize custom titles as something to sort into a department
it ruins readability for the people actually interested in keeping track of the crew monitor and it's bothered me for so long yet i can't diagnose a fix for it myself because i'm stupid as fuck

**Comment by WoolyAypa** [comment]
That'll be fixed upstream :³

**Comment by zeroisthebiggay** [comment]
> That'll be fixed upstream :³

you're my best friend
