### ISSUE TITLE
[BOUNTY] sex spells and magic user quirk 70$ code + 50$ for the sprites

### ISSUE THREAD

**Issue by catrock31** [SPLURT-Station/S.P.L.U.R.T-Station-13#801]
## About the Bounty

Spells id like added and a quirk that gives you them

A spell that grows whoever it is applied to cock to grow buy 10 inches for 15 mins |
 need the spell button
some sort of stimulation spell that uses basic groping and fingering on the target |
 need effect around the target, something to replace your courser while your selecting the target, and the spell button
eyes of lust spell (more of a toggle) that lets you see the arousal of those around you like a med HUD but pink for lust |
 the spell button and the HUD overlay
probably a hypnotism one at range for those who like that sort of thing |
 the spell button and something to replace your courser while your selecting the target
An aura that makes people close (5x5 around)  to the user rapidly gain arousal up to 30% |
 the spell button and the aura
Force equips a something like a gear harness that can't be removed for some amount of time and are naked and something to block the over suit |
 the spell button and the magic harness

**Comment by ImmovableSaint** [comment]
I feel like some of these things would break our rules

**Comment by catrock31** [comment]
> I feel like some of these things would break our rules

fecken add some toggles to let sex magic work on you or no
