### ISSUE TITLE
[BOUNTY] Finish the harddel checker pr ($70)

### ISSUE THREAD

**Issue by BongaTheProto** [SPLURT-Station/S.P.L.U.R.T-Station-13#893]
## Contact:
mos_ley on discord.

## About the Bounty
So, a few months ago an attempt was made to port TG's harddel unit test to check that no items in the game were runtiming upon deletion https://github.com/SPLURT-Station/S.P.L.U.R.T-Station-13/pull/709. This was intended to reduce the amount of harddels and therefore boost server performance a lot. However, due to this requiring a review of almost the entire codebase to check for runtime errors and harddels, this pr remains currently unfinished.

This bounty consists on finishing said pr, fixing all of the things in it causing the check to fail so that the unit test may succeed. It's currently been properly ported but now the part that's left is actually adequating the codebase to pass it. If possible, make fixes related to cit, sandstorm and splurt code in three different commits in the same pr.

I'm willing to discuss the price.

**Comment by miguelop1** [comment]
that sounds like hell comrade

**Comment by Tsurupeta** [comment]
I'll see what I can do...
